### ISSUE TITLE
UpdateDatabaseWithRelationalObjects opdelen

### ISSUE THREAD

**Issue by BpKlomp** [OrdinaNederland/Stichting-NUTwente#478]
De functie UpdateDatabaseWithRelationalObjects is momenteel 150~ regels lang. 
Deze moet voor foutgevoeligheid, onderhoudbaarheid en leesbaarheid gesplitst worden. 

- [x] UpdateDatabaseWithRelationalObjects roept meerdere (het liefst iig 4) subfuncties aan

**Comment by CasperHooft** [comment]
[#478UpdateDatabaseWithRelationalObjects opdelen.xlsx](https://github.com/OrdinaNederland/Stichting-NUTwente/files/9307342/478UpdateDatabaseWithRelationalObjects.opdelen.xlsx)
