### ISSUE TITLE
 formulier "BeschikbareGastgezinnen" Zoeken en filteren op buddy

### ISSUE THREAD

**Issue by stefjoosten** [OrdinaNederland/Stichting-NUTwente#506]
Als coördinator heb ik soms overzichten per buddy nodig. Het zou helpen als ik op het formulier "BeschikbareGastgezinnen" kan sorteren op buddy, net zoals ik dat al kan bij "Intakeplanning".

- [x] Buddy toevoegen aan het dropdown menu van de "BeschikbareGastgezinnen" zoek functie.
- [x] Wanneer deze geselecteerd is deze lijst filteren op de naam van de buddy.

**Comment by CasperHooft** [comment]
Dit zit huidig in het product voor alle rollen behalve vrijwilliger. Het is dus naast zoals beschreven is in deze issue (coordinator) ook beschikbaar voor superAdmin en scretariaat. 

De feature is NIET hoofdletter gevoelig dus als een gebruiker "niek" invoert vindt het zowel de buddy niek als Niek
