### ISSUE TITLE
Mail naar buddy bij verwijdering van gastgezin

### ISSUE THREAD

**Issue by basplijnaer** [OrdinaNederland/Stichting-NUTwente#581]
**Is your feature request related to a problem? Please describe.**
Momenteel weet de buddy van een gastgezin het niet meteen als een gastgezin is verwijderd.

**Describe the solution you'd like**
Een mail naar de buddy op het moment dat de coordinator een gastgezin van de buddy verwijdert.

**Comment by CasperHooft** [comment]
[Testen mails.xlsx](https://github.com/OrdinaNederland/Stichting-NUTwente/files/9306962/Testen.mails.xlsx)
Tests die zijn uitgevoerd
