### ISSUE TITLE
Changing functionality mailhelper & mailservice

### ISSUE THREAD

**Issue by JesseZwitserlood** [OrdinaNederland/Stichting-NUTwente#627]
The words "mailhelper" and "mailservice" have been used in the code in precisely the opposite way as should be.
This can be confusing for future readers of the code, so I want to change this.
The obvious thing is to massively search and replace these words, but I fear there is a little more work to it...

**Comment by CasperHooft** [comment]
[Testen mails.xlsx](https://github.com/OrdinaNederland/Stichting-NUTwente/files/9306962/Testen.mails.xlsx)
Tests die zijn uitgevoerd
