### ISSUE TITLE
Downloads: Vertrokken vluchtelingen statistieken toevoegen aan "Gastgezinnen per gemeente"

### ISSUE THREAD

**Issue by basplijnaer** [OrdinaNederland/Stichting-NUTwente#658]
**Is your feature request related to a problem? Please describe.**
Vanuit de coordinator van NuTwente kwam de volgende vraag of de statistieken over de vertrokken vluchtelingen ook aan het download document "Gastgezinnen per gemeente" toegevoegd kon worden.

**Describe the solution you'd like**
Secretariaat, coordinator en Super users moeten de statistieken over de vertrokken vluchtelingen kunnen downloaden.

DoD
- [x] De statistieken over de vertrokken vluchtelingen zijn te vinden in het document "Gastgezinnen per gemeente" onder de overzichtstekst van het aantal geplaatste vluchtelingen voor Secretariaat, coordinator en Super users.

**Comment by CasperHooft** [comment]
[#658Tests.xlsx](https://github.com/OrdinaNederland/Stichting-NUTwente/files/9307557/658Tests.xlsx)

**Comment by CasperHooft** [comment]
Na het bespreken met de groep is besloten de secretariaat ook toegang te geven tot de download functionaliteit.
Hierdoor zijn nu alle test cases correct.
[#658Tests.xlsx](https://github.com/OrdinaNederland/Stichting-NUTwente/files/9307832/658Tests.xlsx)
