### ISSUE TITLE
Microsoft Graph Connection voor de gegevens in het vak Woonadres

### ISSUE THREAD

**Issue by basplijnaer** [OrdinaNederland/Stichting-NUTwente#678]
Binnen deze issue focussen we allleen op de informatie in het vak Woonadres. Ter verduidelijking is een screenshot opgenomen met een rood vak om de bedoelde informatie.
![Ter verduidelijking Issue 678](https://user-images.githubusercontent.com/107199015/184872368-b02ff2f8-6850-4d7c-8e57-c95df4d5695c.png)

**Is your feature request related to a problem? Please describe.**
Het is momenteel niet mogelijk om de rollen van gebruikers aan te passen vanuit de web applicatie (#79). Ook kunnen andere gegevens die in Azure ADB2C staan (telefoonnummer, naam) niet door coördinatoren aangepast worden. Dit zorgt er voor dat er altijd developers nodig zijn om aanpassingen te maken aan gebruikers en dat er soms aanpassingen verloren gaan.

Extra verduidelijking rollen
De rollen vrijwilligers en secretariaat hebben het recht hun eigen data aan te passen. Met behulp van deze feature zou dat ook in de azure database aanpassingen moeten maken.

De rollen Coordinator en Super-user hebben het recht hun eigen maar ook andermans data aan te passen. Met behulp van deze feature zou dat ook in de azure database aanpassingen moeten maken.

Extra verduidelijking waar de informatie aangepast wordt
De informatie wordt op de Azure database aangepast.
Hier kan je komen door de volgende stappen uit te voeren

1. Ga naar de directory ADB2C 
2. Ga naar groups
3. Selecteer de group waarin de user zich bevind (vrijwilliger/secretariaat/coordinator/superadmin)
4. Klik op members
5. Selecteer het persoon om de data van dat persoon in te zien

**Describe the solution you'd like**
Microsoft Graph implementeren zodat Azure AD gegevens vanuit de webapplicatie kunnen worden aangepast.

**Comment by CasperHooft** [comment]
Bij het testen worden geen foutieve of grote gegevens ingevoerd sinds dit wordt meegenomen in: https://github.com/OrdinaNederland/Stichting-NUTwente/issues/613

**Comment by CasperHooft** [comment]
Test cases voor deze issue. Testing wordt tijdelijk niet uitgevoerd sinds de development omgeving eruit ligt.
[Test#678.xlsx](https://github.com/OrdinaNederland/Stichting-NUTwente/files/9351451/Test.678.xlsx)

**Comment by CasperHooft** [comment]
Het risico bij het invoeren van deze feature in de live branch is dat de huidige informatie wordt strakgetrokken met de Azure database en daardoor informatie verdwijnt is besproken met @basplijnaer.

Hij garandeert dat de enige connectie met Azure zit in het updaten van de adres gegevens in Azure, het wordt er niet meer uit gehaald. Hierdoor valt het risico weg.
