### ISSUE TITLE
Een pull request naar dev maakte niet een pull request naar main aan voor pull 677

### ISSUE THREAD

**Issue by CasperHooft** [OrdinaNederland/Stichting-NUTwente#687]
Bij het mergen naar dev voor pull 677: "https://github.com/OrdinaNederland/Stichting-NUTwente/pull/677" ging er iets fout.

In plaats van een pull request aan te maken naar main die dan approved en dan gemerged kon worden door de tester @CasperHooft. Sloot de pull request zichzelf nadat het gemerged was met de development branch

Als gebruiker van de GIT omgeving wil ik een consistente GIT workflow zodat ik op een constante manier mijn issues kan verwerken.

DoD

- [x] Er is onderzocht waarom/hoe dit gebeurd is
- [x] Er is gedocumenteerd waarom/hoe dit gebeurd is
- [x] Er is een oplossing voor dit probleem gevonden en gedocumenteerd

**Comment by JesseZwitserlood** [comment]
Dit is gebeurd omdat dit process niet geautomatiseerd is maar handmatig is gedaan door Bas.

Bas en Ik hebben na overleg een voorstel opgesteld voor een nieuwe omgeving. In deze omgeving komt een vierde branch namelijk de 'Testing' branch. Het toevoegen van deze branch voorkomt het meegeven van fouten aan de main door te voorkomen dat er veranderingen van andere issues meegenomen worden met een nieuwe merge vanuit development naar main.

de nieuwe situatie zal als volgens werken:

- Wanneer een Developer een issue af heeft maakt deze een pullrequest aan naar development en notificeerd een mede developer hierover. dit zorgt dat er zo snel mogelijk een review over gedaan wordt.
- Na het goedkeuren van de pullrequest merged de reviewer het met development.
- Wanneer de merge complete is maakt de reviewer een pull request aan (indien deze nog niet aanwezig is) van development naar testing. 
- Indien er al een pull request bestaat zorg er dan voor dat het issuenummer als comment toegevoegd word aan het request na het toevoegen van de nieuwe functionaliteit.
- Wanneer de tester toe is aan het testen zal hij dit request goedkeuren en alle tests uitvoeren voor de ontvangen issues.
- ALLEEN wanneer alle issues zijn goedgekeurd zal de tester een merge doen met main
