### ISSUE TITLE
maintainability Repo

### ISSUE THREAD

**Issue by JesseZwitserlood** [OrdinaNederland/Stichting-NUTwente#690]
het process om de repo op te schonen

**Comment by JesseZwitserlood** [comment]
gevonden punten:

- [ ] NuTwente development db connection string uit de repo halen halen

**Comment by CasperHooft** [comment]
Gedurende testing problemen gevonden bij het testen van de site op Firefox.
In plaats van anderhalve minuut duren de automated tests nu veel langer of faalt 1 van de automatische test door time outs.

Huidig onbekend waar dit aan ligt.

**Comment by CasperHooft** [comment]
Driver voor mijn tests "Geckodriver" heeft een issue:https://github.com/mozilla/geckodriver/issues/2040

hierdoor kunnen de tests niet automatisch doorlopen als zij zich niet op de voorgrond bevinden.

Ik heb de tests manueel nagedaan om te valideren dat op firefox de functionaliteit nog wel werkt echter kan deze issue niet automatisch getest worden op firefox browser. 

The automated testing done on the chrome browser are fine and will be implemented for testing this issue.

**Comment by CasperHooft** [comment]
Tests die uitgevoerd zijn:
[Test#690.xlsx](https://github.com/OrdinaNederland/Stichting-NUTwente/files/9424646/Test.690.xlsx)
