### ISSUE TITLE
Separate ADB2C Tenant for Development

### ISSUE THREAD

**Issue by basplijnaer** [OrdinaNederland/Stichting-NUTwente#697]
**Is your feature request related to a problem? Please describe.**
Er is momenteel maar 1 AAD B2C tenant voor beide omgevingen, dit kan de toekomst betekenen dat er productie gegevens in de development omgeving komen.

**Describe the solution you'd like**

- [x] Een tweede AAD B2C tenant aanmaken voor de development omgeving.
- [x] Een tweede Azure Function aanmaken voor het toevoegen van de groepen aan de tokens.
- [x] Production Action aanpassen met de veranderde variabelen.
- [x] Secrets toevoegen voor de veranderde variabelen.
- [x] Development Secret aanpassen met het nieuwe client secret.

**Comment by CasperHooft** [comment]
De uitgevoerd tests:
[Test#697.xlsx](https://github.com/OrdinaNederland/Stichting-NUTwente/files/9394243/Test.697.xlsx)

Daarnaast heeft @CasperHooft de rollen toegekend voor alle test account binnen de development omgeving.
Voor de details check
[Welke accounts zijn er met welke rechten.txt](https://github.com/OrdinaNederland/Stichting-NUTwente/files/9394260/Welke.accounts.zijn.er.met.welke.rechten.txt)
:
