### ISSUE TITLE
Migrate Project Board

### ISSUE THREAD

**Issue by basplijnaer** [OrdinaNederland/Stichting-NUTwente#710]
**Is your feature request related to a problem? Please describe.**
Momenteel wordt als projectboard [Project (Classic)](https://github.com/OrdinaNederland/Stichting-NUTwente/projects?type=classic) gebruikt. GitHub biedt sinds enige tijd een vernieuwde versie van [Projects.](https://github.com/OrdinaNederland/Stichting-NUTwente/projects) Dit zou beter bij het project kunnen passen omdat het onder andere ondersteuning biedt voor verschillende sprints.

**Describe the solution you'd like**
- [ ] Het huidige projectboard migreren (hiervoor zijn rechten nodig binnen de "OrdinaNederland" organisatie)

**Comment by CasperHooft** [comment]
Migrating the project board from classic to current model is live!

Link: https://github.com/orgs/OrdinaNederland/projects/6/views/3
